In [2]:
from sklearn.datasets import load_wine
wines=load_wine()
import numpy as np 
import matplotlib.pyplot as plt

In [27]:
import sklearn
from sklearn.model_selection import train_test_split
X=wines.data
y=wines.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)
type(X)
type(y)

numpy.ndarray

In [28]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)
y_pred_svc = svclassifier.predict(X_test)


In [29]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred_svc))
print(classification_report(y_test,y_pred_svc))
print('Support vector machine accuracy score:', sklearn.metrics.accuracy_score(y_test, y_pred_svc, normalize=True, sample_weight=None)*100)

[[23  0  0]
 [ 1 18  0]
 [ 0  1 11]]
              precision    recall  f1-score   support

           0       0.96      1.00      0.98        23
           1       0.95      0.95      0.95        19
           2       1.00      0.92      0.96        12

   micro avg       0.96      0.96      0.96        54
   macro avg       0.97      0.95      0.96        54
weighted avg       0.96      0.96      0.96        54

Support vector machine accuracy score: 96.29629629629629


In [30]:
from sklearn.naive_bayes import GaussianNB 
gnb = GaussianNB() 
gnb.fit(X_train, y_train) 
y_pred_GNB = gnb.predict(X_test) 
print(confusion_matrix(y_test,y_pred_GNB))
print(classification_report(y_test,y_pred_GNB))
print("Gaussian Naive Bayes model accuracy(in %):", sklearn.metrics.accuracy_score(y_test, y_pred_GNB)*100)

[[23  0  0]
 [ 1 18  0]
 [ 0  0 12]]
              precision    recall  f1-score   support

           0       0.96      1.00      0.98        23
           1       1.00      0.95      0.97        19
           2       1.00      1.00      1.00        12

   micro avg       0.98      0.98      0.98        54
   macro avg       0.99      0.98      0.98        54
weighted avg       0.98      0.98      0.98        54

Gaussian Naive Bayes model accuracy(in %): 98.14814814814815


In [31]:
from sklearn.linear_model import LogisticRegression
LR=LogisticRegression()
LR.fit(X_train, y_train)
y_pred_LR=LR.predict(X_test)
print(confusion_matrix(y_test,y_pred_LR))
print(classification_report(y_test,y_pred_LR))
print("Logistic Regression accuracy(in %):", sklearn.metrics.accuracy_score(y_test, y_pred_LR)*100)


[[22  1  0]
 [ 0 19  0]
 [ 0  1 11]]
              precision    recall  f1-score   support

           0       1.00      0.96      0.98        23
           1       0.90      1.00      0.95        19
           2       1.00      0.92      0.96        12

   micro avg       0.96      0.96      0.96        54
   macro avg       0.97      0.96      0.96        54
weighted avg       0.97      0.96      0.96        54

Logistic Regression accuracy(in %): 96.29629629629629


C:\Users\mailv\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\mailv\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [ ]:
#They all seem to do about the same, 
#but if you change the test size the results will change as well. 
#Same goes for changing the random_state