In [7]:
from sklearn.datasets import load_digits
digits=load_digits()
import numpy as np 
import matplotlib.pyplot as plt

In [8]:
import sklearn
from sklearn.model_selection import train_test_split
X=digits.data
y=digits.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=22)

In [9]:
from sklearn.svm import SVC
svclassifier = SVC(gamma=0.1, kernel='rbf')
svclassifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.1, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [10]:
y_pred = svclassifier.predict(X_test)


In [11]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[ 0  0  0  0  0  0 32  0  0  0]
 [ 0  0  0  0  0  0 40  0  0  0]
 [ 0  0  0  0  0  0 33  0  0  0]
 [ 0  0  0  0  0  0 39  0  0  0]
 [ 0  0  0  0  0  0 44  0  0  0]
 [ 0  0  0  0  0  0 36  0  0  0]
 [ 0  0  0  0  0  0 31  0  0  0]
 [ 0  0  0  0  0  0 30  0  0  0]
 [ 0  0  0  0  0  0 40  0  0  0]
 [ 0  0  0  0  0  0 35  0  0  0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        32
           1       0.00      0.00      0.00        40
           2       0.00      0.00      0.00        33
           3       0.00      0.00      0.00        39
           4       0.00      0.00      0.00        44
           5       0.00      0.00      0.00        36
           6       0.09      1.00      0.16        31
           7       0.00      0.00      0.00        30
           8       0.00      0.00      0.00        40
           9       0.00      0.00      0.00        35

   micro avg       0.09      0.09      0.09       360
   macro avg       

C:\Users\mailv\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [12]:
sklearn.metrics.accuracy_score(y_test, y_pred, normalize=True, sample_weight=None)

0.08611111111111111